---
- name: Add nvidia-docker repository
  get_url:
    url: https://nvidia.github.io/nvidia-docker/{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}/nvidia-docker.repo
    dest: /etc/yum.repos.d/nvidia-docker.repo

- name: Install nvidia-docker2
  yum:
    name: nvidia-docker2
  notify:
    - Reload docker
