---

- name: download prometheus node exporter binary
  get_url:
    url: "{{ url }}"
    dest: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_node_exporter_release_name }}.tar.gz"

- name: unarchive binary tarball
  unarchive:
    copy: no
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_node_exporter_release_name }}.tar.gz"
    dest: "{{ prometheus_exporters_common_dist_dir }}"
    creates: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_node_exporter_release_name }}/node_exporter"
  register: prometheus_node_exporter_updated
  notify:
    - restart node exporter

- name: update group and owner for files
  file:
    path: "{{ prometheus_node_exporter_release_name }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_exporters_common_user}}"
    group: "{{ prometheus_exporters_common_group }}"
  when: prometheus_node_exporter_updated | changed

- name: create symlink to the current release
  file:
    src: "{{ prometheus_exporters_common_dist_dir }}/{{ prometheus_node_exporter_release_name }}"
    path: "{{ prometheus_exporters_common_root_dir }}/node_exporter_current"
    state: link

- name: create systemd service unit
  template:
    src: etc/systemd/system/prometheus-node-exporter.service.j2
    dest: /etc/systemd/system/prometheus-node-exporter.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - reenable node exporter service
    - restart node exporter

- name: Create file_sd_config fragment for prometheus
  template:
    src: file_sd_config.yml.j2
    dest: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"

- name: Retain a copy of the file_sd_config fragment for stats host
  fetch:
    src: "{{ prometheus_exporters_common_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"
    dest: "{{ prometheus_exporters_common_local_sd_conf_dir }}/{{ inventory_hostname }}-node_file_sd_config.yml"
    flat: yes

- meta: flush_handlers

- name: ensure prometheus node exporter service is enabled and started
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
