---
- name: Copy ELREPO repo file
  copy:
    src: elrepo.repo
    dest: /etc/yum.repos.d/elrepo.repo

- name: Copy ELREPO repo gpg key
  copy:
    src: RPM-GPG-KEY-elrepo.org
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org

- name: Install elrepo_nvidia packages
  yum:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      update_cache: yes
  with_items: '{{ elrepo_nvidia_packages }}'
  notify:
    - Modprobe nvidia

- name: Force handlers to run
  meta: flush_handlers
