---
# These facts overlap with definitions from the apache role. Other roles can
# use these facts to work with either version of apache
- name: Remove/disable system httpd
  yum:
    name:
      - httpd
      - mod_ssl
    state: absent

- name: Set httpd service name
  set_fact:
    apache_service: "{{ apache_service }}"

- name: Set httpd server config root
  set_fact:
    apache_server_root: "{{ apache_server_root }}"

- name: Set httpd document root
  set_fact:
    apache_document_root: "{{ apache_document_root }}"

- name: Set httpd server virtualhost config root
  set_fact:
    apache_conf_path: "{{ apache_conf_path }}"

- name: Set httpd server log dir
  set_fact:
    apache_log_dir: "/var/log/httpd24"

- name: Install httpd24-httpd from SCL
  yum:
    name: "{{ httpd24_httpd_packages }}"
    state: present

- name: Install httpd24-modules
  yum:
    name: "{{ httpd24_httpd_modules }}"
    state: present

- name: Configure base
  copy:
    src: '{{ item }}'
    dest: '{{ apache_conf_path }}/'
  with_items:
    - welcome.conf
    - ssl.conf
    - autoindex.conf
    - userdir.conf

- name: Remove mpm-prefork config
  copy:
    src: '00-mpm.conf'
    dest: '{{ apache_server_root }}/conf.modules.d/00-mpm.conf'

- name: Apache 2.4 SCL | set apache service status
  service:
    name: "{{ httpd24_httpd_service_name }}"
    state: "{{ httpd24_httpd_service_status }}"
    enabled: "{{ httpd24_httpd_service_enabled }}"
