---
- name: Add storage in the zpool
  command: /sbin/zfs create '{{ zfs_pool_name }}'/grafana
  args:
    creates: '/{{ zfs_pool_name }}/grafana'
  when: zfs_vdev_config is defined

- name: Add grafana storage and configuration locations
  file:
    path: '{{ item.path }}'
    state: 'directory'
    owner: '{{ grafana_user_uid }}'
    group: '{{ grafana_user_gid }}'
    mode: '{{ item.mode }}'
  with_items:
    - { 'path': '/tank/grafana', 'mode': '0755' }

- name: Add a network for grafana container
  docker_network:
    name: '{{ grafana_network }}'

- name: Start grafana/grafana container
  docker_container:
    image: '{{ grafana_image }}:{{ grafana_image_tag }}'
    name: '{{ grafana_name }}'
    user: '{{ grafana_user_uid }}'
    ports: '{{ grafana_listen_address }}:{{ grafana_internal_port }}:{{ grafana_external_port }}'
    state: started
    network_mode: 'host'
    env: { 
      'GF_SERVER_ROOT_URL': '{{ grafana_root_url }}',
      'GF_SERVER_DOMAIN': '{{ grafana_domain }}',
      'GF_SMTP_ENABLED': 'true',
      'GF_SMTP_FROM_ADDRESS': '{{ grafana_email }}'
    }
    volumes: 
      - /tank/grafana:/var/lib/grafana:rw
