---
- name: add apache vhost configuration
  template:
    src: metrics.conf.j2
    dest: /etc/httpd/conf.d/metrics.conf
    owner: root
    group: root
    mode: 0644
  notify: graceful apache

- name: Collect DNS name of stats_host
  shell: "getent hosts {{ metrics_host }} | cut -d' ' -f 1"
  register: metrics_ip_address
  changed_when: false

- name: Add stats host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?(\.|$){4}\b {{ metrics_host }}'
    line: '{{ metrics_ip_address.stdout }} {{ metrics_host }}'
