# This needs to be either dynamic (somehow) or assembled from fragments
# defined by each new host
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-stats.syzygy.ca'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'container-exporter'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'node.syzygy.ca'
    scheme: 'https'
    file_sd_configs:
      - files:
        - tgroups/*-node_file_sd_config.yml
  
  - job_name: 'cadvisor.syzygy.ca'
    scheme: 'https'
    file_sd_configs:
      - files:
        - tgroups/*-cadvisor_file_sd_config.yml
  
  - job_name: 'jupyterhub.syzygy.ca'
    scheme: 'https'
{% if jupyterhub_stats_api_token is defined %}
    bearer_token: '{{ jupyterhub_stats_api_token.token }}'
{% endif %}
    file_sd_configs:
      - files:
        - tgroups/*-jupyterhub_file_sd_config.yml
