---
- name: Ensure sudo is configured correctly
  hosts: stats
  become: true
  tasks:
    # Settings are defined in
    # group_vars/<group>/sudo.yml
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo
      vars:
          ansible_ssh_pipelining: no

- name: Install and configure the 
  hosts: stats
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      include_role:
        name: hostname

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      include_role:
        name: ssh-public-keys

    # This also installs EPEL
    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    - name: Configure SELinux
      tags: ["selinux"]
      include_role:
        name: selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    # Enabled services are defined in
    # group_vars/hub/firewalld.yml
    #
    - name: Ensure firewalld service is running
      tags: ["firewalld"]
      include_role:
        name: flatkey.firewalld

    # Configuration is stored in
    # group_vars/<group>/ssh.yml.
    - name: Ensure sshd is installed and running
      tags: ["sshd"]
      include_role:
        name: sshd

    # Configuration is stored in
    # group_vars/<group>/httpd.yml
    - name: Manage Apache
      tags: ["httpd"]
      include_role:
        name: httpd24-httpd

    # This requires the hub to have a resolvable FQDN.
    - name: Configure letsencrypt
      tags: ["ssl", "letsencrypt", "httpd"]
      include_role:
        name: dehydrate-letsencrypt

    - name: Manage Python3
      tags: ["python", "python3"]
      include_role:
        name: python36

    # Manage Docker
    - name: Manage Docker
      include_role:
        name: docker

    - name: Manage Docker extra
      include_role:
        name: docker-extra

    - name: update facts if docker0 is not defined
      action: setup filter="ansible_docker0"
      when: ansible_docker0 is not defined

    - name: Install docker module
      yum:
        name: 'python-docker-py'
        state: 'present'

    - name: Manage Docker storage
      include_role:
        name: docker-storage

    - name: Manage prometheus
      include_role:
        name: prometheus

    - name: Manage grafana
      include_role:
        name: grafana

