## Update all packages (MAY REBOOT)
- name: Update Packages
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      ignore_errors: true
      when: "not disable_update | default(false)"

    - name: Check needs-restarting status
      command: needs-restarting -r
      register: command_restart
      failed_when: command_restart.rc not in [0, 1]
      check_mode: no
      changed_when: command_restart.rc == 1

    - name: Reboot instance
      reboot:
        reboot_timeout: 300
        pre_reboot_delay: 30
        post_reboot_delay: 30
      when: command_restart.rc == 1

