## Manages a JuptyerHub installation
---
- name: Setup generic environment
  hosts: hub
  tasks:
    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      ansible.posix.authorized_key:
        user: "{{ item.value.user }}"
        state: "{{ item.value.state }}"
        key: "{{ item.value.public_key }}"
      loop: "{{ ssh_public_keys | dict2items }}"
      when: ssh_public_keys is defined

    - name: Install Base Packages
      become: true
      tags: ["base-packages"]
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ base_packages }}"
      when: base_packages | length > 0

    - name: Set SELinux as permissive
      become: true
      ansible.posix.selinux:
        policy: targeted
        state: permissive
    
    - name: Update all packages
      become: true
      ansible.builtin.yum:
        name: "*"
        state: latest
      ignore_errors: true
    - name: Check needs-restarting status
      become: true
      ansible.builtin.command: needs-restarting -r
      register: command_restart
      failed_when: command_restart.rc not in [0, 1]
      check_mode: no
      changed_when: false

    - name: Reboot instance
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 300
        pre_reboot_delay: 30
        post_reboot_delay: 30
      when: command_restart.rc == 1

- name: Apply roles
  hosts: hub
  pre_tasks:
    - name: Install sudo
      become: yes
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Configure sudoers defaults
      become: yes
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        content: "# Ansible managed\nDefaults !requiretty\n"
        validate: /usr/sbin/visudo -cf %s
        owner: root
        group: root
        mode: "0440"

  roles:
    - { role: geerlingguy.repo-epel, become: yes }
    - { role: devsec.hardening.ssh_hardening, become: yes }

    - role: zfs
      become: true
      tags:
        - zfs

    - role: zfs-snapshot
      become: true
      tags:
        - zfs
