---
- name: Install HTML files
  git:
    repo: '{{ syzygy_hub_landing_page_repo }}'
    version: "{{ syzygy_landing_branch }}"
    dest: '{{ syzygy_html_dir.src }}'
    ssh_opts: "-o StrictHostKeyChecking=no"
  notify:
    - Copy landing page templates
    - Update image assets

- name: Check if target exists
  stat:
    path: '{{ syzygy_html_dir.dest }}'
  register: site_exists

- name: Rebuild site if target missing
  debug:
    msg: "Site content missing, rebuilding"
  notify: 
    - Copy landing page templates
    - Update image assets
  changed_when: site_exists.stat.exists == false

- name: Flush handlers
  meta: flush_handlers

- name: Grab html template from host
  run_once : true
  fetch:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    flat: yes
    fail_on_missing: yes
  with_items:
    - src: '{{ syzygy_html_dir.src }}/index.html'
      dest: '/var/tmp/syzygy-html-index.html'
    - src: '{{ syzygy_html_dir.src }}/logout/index.html'
      dest: '/var/tmp/syzygy-html-logout-index.html'

- name: Process html template and send results back to host
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - dest: '{{ syzygy_html_dir.dest }}/index.html'
      src: '/var/tmp/syzygy-html-index.html'
    - dest: '{{ syzygy_html_dir.dest }}/logout/index.html'
      src: '/var/tmp/syzygy-html-logout-index.html'

- name: Update DocumentRoot
  notify:
    - restart apache
  lineinfile:
    dest: '{{ apache_server_root }}/conf/httpd.conf'
    regexp: '^DocumentRoot'
    line: 'DocumentRoot "{{ syzygy_html_dir.dest }}"'

- name: Add httpd config for jupyter service
  template:
    src: jupyter-http.conf.j2
    dest: '{{ apache_conf_path }}/jupyter.conf'
    mode: 0644
    owner: root
    group: root
  notify: restart apache
