---
# Add ansible user to docker group
- name: Add user to docker group
  user:
    name: '{{ docker_user }}'
    groups: '{{ docker_group }}'
    append: yes

- name: Add container-renice script
  copy:
    src: container-renice.sh
    dest: /usr/local/bin/container-renice
    owner: root
    group: root
    mode: '0755'
