---
httpd24_httpd_packages:
  - httpd24

httpd24_httpd_modules:
  - httpd24-mod_ssl

httpd24_httpd_service_name: httpd24-httpd
httpd24_httpd_service_status: started
httpd24_httpd_service_enabled: yes

apache_service: httpd24-httpd
apache_server_root: /opt/rh/httpd24/root/etc/httpd
apache_conf_path: /opt/rh/httpd24/root/etc/httpd/conf.d
apache_document_root: /opt/rh/httpd24/root/var/www/html
