# This needs to be either dynamic (somehow) or assembled from fragments
# defined by each new host
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-stats.syzygy.ca'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'container-exporter'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'syzygy.ca'
    file_sd_configs:
      - files:
        - tgroups/*.yml
