---
- name: Remove existing certs
  listen: "Run dehydrate"
  file:
    path: '~{{ acme_user }}/certs/{{ inventory_hostname }}/'
    state: absent

- name: Run dehydrate
  listen: "Run dehydrate"
  shell: '~{{ acme_user }}/wrapper.sh'
