---
roles:
  - name: geerlingguy.repo-epel
    version: 3.1.1
  - name: geerlingguy.docker
    version: 8.0.0
  - name: geerlingguy.ansible
    version: 2.3.0
  - name: geerlingguy.apache
    version: 4.2.0
  - name: geerlingguy.nodejs
    version: 7.1.0
  - name: willshersystems.sshd
    version: v0.31.0
  - name: weareinteractive.sudo
    version: 1.14.1

collections:
  - name: ansible.posix
    version: 2.1.0
    source: https://galaxy.ansible.com
  - name: community.general
    version: 12.2.0
    source: https://galaxy.ansible.com
  - name: devsec.hardening
    version: 10.5.0
    source: https://galaxy.ansible.com
  - name: prometheus.prometheus
    version: 0.27.5
    source: https://galaxy.ansible.com
  - name: grafana.grafana
    version: 6.0.6
