---
- name: deamon reload
  command: systemctl daemon-reload

- name: Start JupyterHub
  service:
    name: jupyterhub
    enabled: yes
    state: started

- name: Restart CHP
  service:
    name: configurable-http-proxy
    state: restarted

- name: Restart JupyterHub
  service:
    name: jupyterhub
    state: restarted
